"""Init

Revision ID: 96e5a4c3cd5f
Revises: 
Create Date: 2024-09-21 05:11:20.811976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96e5a4c3cd5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    with op.batch_alter_table('ambulance', schema=None) as batch_op:
        batch_op.drop_index('license_plate')

    op.drop_table('ambulance')
    op.drop_table('emergency_request')
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['emt_id'], ['id'])
        batch_op.drop_column('patient_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_info', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('emt_id')

    op.create_table('emergency_request',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospital_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('emergency_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='emergency_request_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ambulance',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('license_plate', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ambulance', schema=None) as batch_op:
        batch_op.create_index('license_plate', ['license_plate'], unique=True)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
