"""asd

Revision ID: a398e82abd8b
Revises: 43f80857053d
Create Date: 2024-09-20 14:47:19.788521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a398e82abd8b'
down_revision = '43f80857053d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emt_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['emt_id'], ['id'])
        batch_op.drop_column('patient_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_info', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('emt_id')

    # ### end Alembic commands ###
