"""asd

Revision ID: b159ab49b969
Revises: a398e82abd8b
Create Date: 2024-09-20 14:49:43.564023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b159ab49b969'
down_revision = 'a398e82abd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
